apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pce-web
  description: Find where your juice comes from
  links:
    - url: https://github.com/volvo-cars/bakery-docs
      title: PCE Offerings
      icon: "techdocs"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - azure
    - pce
spec:
  type: documentation
  lifecycle: production
  owner: nietakipawel
