site_name: "PCE-Innovation-Week"
site_description: "Describes the 3Scale platform from ICoE and how to use it "
nav:
  - Overview: index.md
  - Availability of API management gateways: gateways.md
  - Availability of Supporting components: components.md

plugins:
  - techdocs-core
