apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding
  title: Azure Onboarding
  description: Onboard to Azure
  tags:
    - azure
spec:
  owner: nietakipawel
  type: service
  parameters:
   - title: We need few params from you
      required:
        - azure_object_id
      properties:
        azure_object_id:
          title: RG Name
          type: string
          description: The object ID for the group in Azure active directory that matches your team
        platform:
          title: Platform name
          type: string
          description: Select the preferred platform for Sentry Project
          default: none
          enum:
          - westeurope
          - westus
  steps:
    - id: run-onboarding
      name: Run onboarding
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=backstage_playground&owner=CloudSpotPL'
        workflowId: 'blank.yaml'
        branchOrTagName: 'main'
        workflowInputs:
          azure_object_id: ${{ parameters.azure_object_id }}
          location: ${{ parameters.platform }}
    - id: log
      needs: run-onboarding
      name: Result
      action: debug:log
      input:
        message: |
          RG created
