apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding
  title: Create Azure Resource Group
  description: Create Azure Resource Group
  tags:
    - azure
    - resource-group
    - azure-quickstart
spec:
  owner: pce-azure
  type: service
  partof: ['component:pce-azure-platform-offerings']
  parameters:
    - title: You are about to request Azure Resource Group creation
      required:
        - rg_name
      properties:
        rg_name:
          title: Provide your project name
          type: string
          description: Your project ID
  steps:
    - id: run-onboarding
      name: Run onboarding
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=backstage_playground&owner=CloudSpotPL'
        workflowId: 'blank.yaml'
        branchOrTagName: 'main'
        workflowInputs:
          azure_object_id: ${{ parameters.rg_name }}
  output:
    links:
      - title: Check status of your onboarding at
        url: https://github.com/CloudSpotPL/backstage_playground/actions
