apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding
  title: Azure Onboarding
  description: Onboard to Azure
  tags:
    - azure
spec:
  owner: nietakipawel
  type: service

  parameters:
    - title: We need few params from you
      required:
        - azure_object_id
        - location
      properties:
      - azure_object_id:
          title: Object ID for your team
          type: string
          description: The object ID for the group in Azure active directory that matches your team
      - volume_type:
          title: Volume Type
          type: string
          description: The volume type to be used
          default: gp2
          enum:
            - westeurope
            - westus
        enumNames:
          - 'General Purpose SSD (gp2)'
          - 'General Purpose SSD (gp3)'
  steps:
    - id: run-onboarding
      name: Run onboarding
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=backstage_playground&owner=CloudSpotPL'
        workflowId: 'blank.yaml'
        branchOrTagName: 'main'
        workflowInputs:
          azure_object_id: ${{ parameters.azure_object_id }}
    - id: log
      needs: run-onboarding
      name: Result
      action: debug:log
      input:
        message: |
          RG created
