on:
  workflow_dispatch:
    inputs:
      rg_name:
        required: true
permissions:
  id-token: write
  contents: read

name: Create resource
run-name: Create resource rg-${{ github.event.inputs.rg_name }}
jobs:
 create_rg:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to Azure using Federated Credentials'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Create Resource Group'
        run: |
          az group create -n 'rg-${{ github.event.inputs.rg_name }}' --location westus

