on:
  workflow_dispatch:
    inputs:
      st_name:
        required: true
permissions:
  id-token: write
  contents: read

name: Create resource
run-name: Create resource ${{ github.event.inputs.st_name }}
jobs:
  create:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Creating storage account'
        run: |
          echo FOO=foobar--$(date +%s) >> $GITHUB_ENV
          az group create -n 'rg-${{ github.event.inputs.st_name }}-${{env.FOO}}' --location westus
      
          az storage account create -n 'st${{ github.event.inputs.st_name }}${{env.FOO}}' -g 'rg-${{ github.event.inputs.st_name }}-${{env.FOO}}' -l westus --sku Standard_LRS --public-network-access Disabled

